#!/usr/bin/env python3

import os.path
import sys
from rich.table import Table
from rich.console import Console
from operator import itemgetter



sys.path.insert(0, os.path.expanduser('~/.config/qtile/'))

from config import keys

keyslist = []
table = Table()

table.add_column('Modifier', style="cyan")
table.add_column('Key', style="magenta")
table.add_column('Desc', style="green")

for key in keys:
    keyslist.append([' + '.join(key.modifiers), key.key, key.desc])

keyslist.sort(key=itemgetter(1))

for row in keyslist:
    table.add_row(row[0],row[1],row[2])

console = Console()
console.print(table)


